### ISSUE TITLE
[all dokis] most poems broken

### ISSUE THREAD

**Issue by monika348** [monika348/dokis#47]
most to all of the poems you can ask for either do not reply, or error out on request
![image](https://user-images.githubusercontent.com/42224091/62151302-06e21e00-b2ce-11e9-97ee-e6d4de7abd44.png)
![image](https://user-images.githubusercontent.com/42224091/62151331-1497a380-b2ce-11e9-8b85-07a916bd36cf.png)

**Comment by tangalbert919** [comment]
@Cheezy096 stay out of my way on this one.

**Comment by Cheezy096** [comment]
Alright pushy

**Comment by tangalbert919** [comment]
Natsuki is ready to go. Now for the rest of the dokis.

**Comment by sayori3** [comment]
> Natsuki is ready to go. Now for the rest of the dokis.

Alright that's a good start!

**Comment by tangalbert919** [comment]
Finished. Adding to v2.2.1 changelog.
