### ISSUE TITLE
debug commands broken

### ISSUE THREAD

**Issue by monika348** [monika348/dokis#49]
Debug commands error out on public side
![image](https://user-images.githubusercontent.com/42224091/62220652-65ff6b80-b37e-11e9-9d30-17d9793dd035.png)

**Comment by monika348** [comment]
Still an error, cheezy did not fix it as we discovered before, just deleted the shard checks from existance

**Comment by tangalbert919** [comment]
~~Of course he did that. He doesn't know how to fix his own code.~~ I fixed this problem.

**Comment by monika348** [comment]
> ~Of course he did that. He doesn't know how to fix his own code.~ I fixed this problem.

Oh you fixed the debug commands with adding sharding back

**Comment by tangalbert919** [comment]
I'm just going to close this, because it's already fixed.
